agent_address = "/tmp/spire-agent/public/api.sock"
cert_dir = "/certs"
daemon_mode = true
svid_file_name = "svid.pem"
svid_key_file_name = "svid_key.pem"
svid_bundle_file_name = "svid_bundle.pem"
cert_file_mode = 420
key_file_mode = 420
