# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0-standalone-strict/serviceaccount-v1.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tayga
  namespace: nat64
  labels:
    app.kubernetes.io/name: tayga
    app.kubernetes.io/component: nat64
