[workspace]
resolver = "3"
members = ["services/gateway", "services/identity"]

[workspace.package]
version = "0.1.0"

[workspace.metadata.crane]
name = "home-ryanseipp"

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }

[workspace.dependencies]
async-trait = "0.1.89"
aws-lc-rs = "1.16.1"
base64ct = { version = "1.8.3", features = ["alloc"] }
prost = "0.14.3"
prost-types = "0.14.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["full"] }
tonic = "0.14.5"
tonic-prost = "0.14.5"
tonic-prost-build = "0.14.5"
uuid = { version = "1.22.0", features = ["v4", "v7"] }
zeroize = { version = "1.8.2", features = ["derive"] }

# Configuration
config = { version = "0.15.19", default-features = false }

# Database
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "tls-rustls-aws-lc-rs", "postgres", "migrate", "macros", "uuid", "json", "chrono"] }

# Logging
json-subscriber = { version = "0.2.7", default-features = false, features = ["tracing-opentelemetry-0-32"] }

# TLS
rcgen = { version = "0.14.7", default-features = false, features = ["aws_lc_rs", "pem"] }
rustls = { version = "0.23.37", default-features = false }

# Kafka
rskafka = { version = "0.6.0", default-features = false }

# HTTP Framework
axum = "0.8.8"
tower = { version = "0.5.3", features = ["util"] }
tower-http = { version = "0.6.8", features = ["trace", "cors"] }
hyper = { version = "1.8.1", features = ["server", "http1", "http2"] }
hyper-util = { version = "0.1.20", features = ["tokio", "server-auto", "http1", "http2"] }

# TLS
tokio-rustls = { version = "0.26.4", default-features = false, features = ["aws-lc-rs"] }
rustls-pemfile = "2.2.0"

# Server
tokio-stream = { version = "0.1.18", features = ["net"] }
tokio-util = { version = "0.7.18", features = ["rt"] }

# Observability
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
opentelemetry = "0.31.0"
opentelemetry_sdk = { version = "0.31.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.31.0", default-features = false, features = ["grpc-tonic", "trace", "metrics"] }
tracing-opentelemetry = "0.32.1"
