[workspace]
resolver = "3"
members = ["services/gateway", "services/identity"]

[workspace.package]
version = "0.1.0"

[workspace.metadata.crane]
name = "home-ryanseipp"

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }

[workspace.dependencies]
async-trait = "0.1"
aws-lc-rs = "1"
base64ct = { version = "1", features = ["alloc"] }
prost = "0.14"
prost-types = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tonic = "0.14"
tonic-prost = "0.14"
tonic-prost-build = "0.14"
uuid = { version = "1", features = ["v4", "v7"] }
zeroize = { version = "1", features = ["derive"] }

# Configuration
config = { version = "0.15", default-features = false }

# Database
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "tls-rustls-aws-lc-rs", "postgres", "migrate", "macros", "uuid", "json", "chrono"] }

# Logging
json-subscriber = { version = "0.2", default-features = false, features = ["tracing-opentelemetry-0-32"] }

# TLS
rcgen = { version = "0.14", default-features = false, features = ["aws_lc_rs", "pem"] }
rustls = { version = "0.23", default-features = false }

# Kafka
rskafka = { version = "0.6", default-features = false }

# Server
tokio-stream = { version = "0.1", features = ["net"] }
tokio-util = { version = "0.7", features = ["rt"] }

# Observability
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
opentelemetry = "0.31"
opentelemetry_sdk = { version = "0.31", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.31", default-features = false, features = ["grpc-tonic", "trace", "metrics"] }
tracing-opentelemetry = "0.32"
