[package]
name = "identity"
version = "0.1.0"
edition = "2024"

[features]
default = []
fips = ["aws-lc-rs/fips"]

[dependencies]
async-trait.workspace = true
aws-lc-rs.workspace = true
base64ct.workspace = true
prost.workspace = true
prost-types.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
uuid.workspace = true
zeroize.workspace = true

[dev-dependencies]
jsonwebtoken = { version = "10.3", default-features = false, features = ["rust_crypto"] }
proptest = "1"

[build-dependencies]
tonic-prost-build.workspace = true
