[package]
name = "test-utils"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
# Database
deadpool-postgres.workspace = true
identity = { path = "../identity" }
gateway = { path = "../gateway" }

# Testcontainers
testcontainers.workspace = true
testcontainers-modules.workspace = true

# SPIFFE
spiffe.workspace = true

# Async
tokio.workspace = true

# Misc
serde_json.workspace = true
tempfile.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
